// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	BUN_VERSION: "1.1.45";
	NODE_VERSION: "latest";
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	CLERK_SIGN_UP_URL: string;
	CLERK_SIGN_IN_URL: string;
	CLERK_OCLIENT_ID: string;
	CLERK_OCLIENT_SECRET: string;
	CLERK_URL: string;
}
