// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	APP_URL: string;
	CLERK_CLIENT_ID: string;
	CLERK_CLIENT_SECRET: string;
	CLERK_ISSUER: string;
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	CLERK_SESSION_SECRET: string;
}
