name = "repro"
pages_build_output_dir = "build/client"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

[vars]
BUN_VERSION = "1.1.42"
CLERK_PUBLISHABLE_KEY = ""
CLERK_SIGN_IN_URL = ""
CLERK_SIGN_UP_URL = ""
NODE_VERSION = "latest"
